name: fittest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mock_image.png
    - assets/images/fittin.png
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont.ttf
          weight: 400 # Regular
          style: normal